infobloxopen/konk

- charts/apiserver/.helmignore
- charts/apiserver/Chart.yaml
- charts/apiserver/lint-values.yaml
- charts/apiserver/templates/NOTES.txt
- charts/apiserver/templates/_helpers.tpl
- charts/apiserver/templates/deployment.yaml
- charts/apiserver/templates/hpa.yaml
- charts/apiserver/templates/ingress.yaml
- charts/apiserver/templates/service.yaml
- charts/apiserver/templates/serviceaccount.yaml
- charts/apiserver/templates/tests/test-connection.yaml
- charts/apiserver/values.yaml
Demo:
```
thayward@tac-ml-thayward apiserver % helm3 upgrade -i konk .                                                                                               minikube
Release "konk" has been upgraded. Happy Helming!
NAME: konk
LAST DEPLOYED: Thu Aug 27 15:32:08 2020
NAMESPACE: default
STATUS: deployed
REVISION: 11
NOTES:
1. Get the application URL by running these commands:
export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=apiserver,app.kubernetes.io/instance=konk" -o jsonpath="{.items[0].metadata.name}")
echo "Visit http://127.0.0.1:8080 to use your application"
kubectl --namespace default port-forward $POD_NAME 8080:80
thayward@tac-ml-thayward apiserver % k get po -w …
```
> minimal viable helm chart for apiserver

- charts/konk/templates/deployment.yaml
- charts/konk/templates/etcd-secret.yaml
- charts/konk/values.yaml
demo:
```
% k get po                                                                                                                   minikube
NAME                           READY   STATUS    RESTARTS   AGE
thayward-konk-cdc746cf-vbgvr   2/2     Running   0          76s
```
```
% k logs thayward-konk-cdc746cf-vbgvr apiserver --tail 10                                                                    minikube
I0828 23:06:09.506820       1 storage_scheduling.go:143] all system priority classes are created successfully or already exist.
W0828 23:06:09.549314       1 lease.go:233] Resetting endpoints for master service "kubernetes" to [172.18.0.4]
I0828 23:06:09.550618       1 controller.go:606] quota admission added evaluator for: endpoints
I0828 23:06:09.556961       1 controller.go:606] …
```
> run etcd in same pod as apiserver

- Makefile
- charts/konk/image-tag-values.yaml
To simplify deploying with compatible image versions for any release of k8s, a make target to generate the overrides is provided.
Demo:
```
% make charts/konk/image-tag-values.yaml
apiserver:
image:
tag: v1.19.0
etcd:
image:
tag: 3.4.9-1
```
```
% make charts/konk/image-tag-values.yaml K8S_RELEASE=v1.15.7
apiserver:
image:
tag: v1.15.12
etcd:
image:
tag: 3.3.10
```
> add make target to generate images tag values synced to a k8s release

- charts/konk/scripts/provision.sh
- charts/konk/templates/configmap.yaml
- charts/konk/templates/init-pod.yaml
This allows using the script without the helm chart, such as during local development.
> use environment variables to eliminate requirement of templating inside scripts

- Makefile
- charts/konk/scripts/provision.sh
- charts/konk/templates/init-pod.yaml
- charts/konk/templates/role.yaml
Labels the secrets created by the init pod so that we know which release they belong to.
Demo:
```
% k get secrets --show-labels                                                                                                minikube
NAME                                  TYPE                                  DATA   AGE   LABELS
default-token-4cvd9                   kubernetes.io/service-account-token   3      12d   <none>
sh.helm.release.v1.thayward-konk.v1   helm.sh/release.v1                    1      11s   modifiedAt=1599602297,name=thayward-konk,owner=helm,status=deployed,version=1
thayward-konk-apiserver-cert          Opaque                                4      7s    app.kubernetes.io/instance=thayward-konk,app.kubernetes.io/name=konk
thayward-konk-etcd-cert               Opaque …
```
> label secrets

- Makefile
- charts/konk/templates/deployment.yaml
- charts/konk/templates/tests/test-connection.yaml
- charts/konk/values.yaml
KONK runs an apiserver independently without a node and CNI, so many features of Kubernetes like Deployments are unsupported. This PR disables them so that users will get an error when trying to create these types of resources.
> disable unsupported APIs

- charts/konk/scripts/provision.sh
- charts/konk/templates/deployment.yaml
- charts/konk/templates/tests/test-connection.yaml
- charts/konk/values.yaml
The kubeconfig now trusts the apiserver.
Resolves TODO: https://github.com/infobloxopen/konk/pull/11#discussion_r483897211
> generate certs and kubeconfig with correct service name

- Makefile
- helm-charts/konk/scripts/provision.sh
- helm-charts/konk/templates/role.yaml
Summary of changes - Updated the provision.sh script to add owner references to the secrets linking them to the konk deployment.
DEMO - 
```
sc-ml-avenkata:konk abalavenkata$ make deploy-konk
helm -n ab upgrade -i abalavenkata-konk helm-charts/konk
Release "abalavenkata-konk" does not exist. Installing it now.
NAME: abalavenkata-konk
LAST DEPLOYED: Thu Sep 10 14:47:04 2020
NAMESPACE: ab
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
export POD_NAME=$(kubectl get pods --namespace ab -l "app.kubernetes.io/name=konk,app.kubernetes.io/instance=abalavenkata-konk" -o jsonpath="{.items[0].metadata.name}")
echo "Visit http://127.0.0.1:8080 to use your application"
kubectl --namespace ab port-forward $POD_NAME 8080:80
sc-ml-avenkata:konk abalavenkata$ …
```
> Added ownerReferences to secrets

- helm-charts/konk/scripts/provision.sh
I was seeing errors like this:
```
+ kubectl patch -n default secret test-konk-apiserver-cert -p '{"metadata":{"ownerReferences":[{"apiVersion":"apps/v1", "kind":"Deployment", "name":"test-konk", "uid":"' 'k:{"uid":"1b2afbf1-f5b7-48dd-aee1-fa8d1831423c"}:' f:uid: '{}' : 1b2afbf1-f5b7-48dd-aee1-fa8d1831423c '9364ff59-6372-416c-9666-665698a9828e"}]}}'
Error from server (BadRequest): unexpected EOF
Error from server (NotFound): secrets "k:{\"uid\":\"1b2afbf1-f5b7-48dd-aee1-fa8d1831423c\"}:" not found
Error from server (NotFound): secrets "f:uid:" not found
Error from server (NotFound): secrets "{}" not found
Error from server (NotFound): secrets ":" not found
Error from server (NotFound): secrets "1b2afbf1-f5b7-48dd-aee1-fa8d1831423c" not found
Error from server (NotFound): secrets …
```
> fix owner uid

- .github/workflows/pr.yaml
- Makefile
- helm-charts/konk-operator/values.yaml
- helm-charts/konk/values.yaml
· konk-operator -> ImagePullPolicy is not set to Always
It's recommended to always set the ImagePullPolicy to Always, to
make sure that the imagePullSecrets are always correct, and to
always get the image you want.
> Set best practice Container Image Pull Policy

- helm-charts/konk/templates/deployment.yaml
This adds initial delay to the apiserver liveness probe. ~This should fix the CrashLoopBackoff errors caused by etcd not being ready fast enough before the apiserver liveness probe fails.~ This is only needed on Kubernetes deployments that don't support startupProbe.
Root cause of the liveness probe failing on some environments is because of how their pod networking is configured. In Minikube, it always works. In more traditional deployments, the node needs to be able to access the etcd container's health/metrics port, which requires that it listen on the pod IP, not just localhost.
> fix etcd liveness probe

- helm-charts/konk-operator/dashboards/konk-operator.json
- helm-charts/konk-operator/templates/dashboard.yaml
- helm-charts/konk-operator/values.yaml
This PR adds a CR containing a Grafana dashboard. It looks like this:
> Add a Grafana dashboard

- helm-charts/konk/scripts/provision.sh
I'm seeing errors like this in the provisioning script on older clusters:
```
+ kubectl -n thayward-demo wait --timeout=3m --for=condition=progressing deployment -l app.kubernetes.io/instance=example-konk
Error from server (Forbidden): deployments.extensions is forbidden: User "system:serviceaccount:thayward-demo:example-konk" cannot list resource "deployments" in API group "extensions" in the namespace "thayward-demo"
```
The shorthand `kubectl get deploy` was matching the older deployment api group, `extensions/v1beta1`, but the rbac only has permission on `apps`. If we explicitly request `deployments.apps`, it succeeds.
> Fix deployment rbac

- .github/workflows/pr.yaml
- Makefile
- config/rbac/role.yaml
- helm-charts/konk/scripts/provision.sh
- helm-charts/konk/templates/certificate.yaml
- helm-charts/konk/templates/issuer.yaml
- jetstack-index.yaml
- repositories.yaml
Added code to create an Issuer and Certificate (Cert-manager CRDs), which creates a secret to be referenced to by service ingress object.
Generates the following objects - 
Issuer - 
```
konk abalavenkata(k8s: minikube) $ kubectl get issuer -n ab -o yaml
apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
annotations:
meta.helm.sh/release-name: abalavenkata-konk
meta.helm.sh/release-namespace: ab
creationTimestamp: "2020-09-25T04:13:24Z"
generation: 1
labels:
app.kubernetes.io/managed-by: Helm
name: abalavenkata-konk-ca-issuer
namespace: ab
resourceVersion: "2374043"
selfLink: /apis/cert-manager.io/v1/namespaces/ab/issuers/abalavenkata-konk-ca-issuer
uid: d895ff41-4850-427f-bc93-03e04e5faff4
spec:
ca:
secretName: abalavenkata-konk-ca
status:
conditions:
- …
```
> Create Issuer and Certificate resources for allowing public authenticated traffic

- helm-charts/konk/scripts/provision.sh
Fix for - https://infoblox.atlassian.net/browse/ATLAS-8136
Looks like the `provision.sh` script was expecting the deployment label `app.kubernetes.io/instance` to hold the fullname (Release Name + Chart Name) instead of just the release-name. This caused a conflict with the selectorLabels value which stores the release-name.
DEMO - 
Existing behavior -
```
kubectl -n default wait --timeout=3m --for=condition=progressing deployments.apps -l app.kubernetes.io/instance=example-konk
error: no matching resources found
```
Deployed a test Konk with the name - example. Observed the logs below in init container.
```
kubectl -n default wait --timeout=3m --for=condition=progressing deployments.apps -l app.kubernetes.io/instance=example
deployment.apps/example-konk condition met …
```
> Fix Provision.sh script

- helm-charts/konk-service/templates/certificate.yaml
Fixes the error:
E1024 00:41:26.255482       1 controller.go:116] loading OpenAPI spec for "v1alpha1.tagging.bulk.infoblox.com" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: error trying to reach service: x509: certificate is valid for tagging-api-tagging-apiserver-apiservice-konk-service, tagging-api-tagging-apiserver-apiservice-konk-service.tagging-v2, tagging-api-tagging-apiserver-apiservice-konk-service.tagging-v2.svc, not tagging-api-tagging-apiserver-apiservice.tagging-v2.svc
> Use the service name in the certificate dns names

- helm-charts/konk-service/templates/configmap.yaml
- helm-charts/konk/scripts/provision.sh
By using the exact release name (not a template) to build the kubeconfig name, it is easier for other charts that need to reference that kubeconfig to predict the secret name. Before this, the logic of the fullname template would sometimes insert `-konk` into the name and sometimes not, making it difficult to predict (dependent charts do not have access to konk's fullname template use it to generate the secret name directly).
> Don't put -konk in kubeconfig name

- helm-charts/konk/values.yaml
Ideally, all users of the Konk CR would define right-size resources for konk's containers in their Konk spec, but I don't realistically expect this to happen. Reasonable default values, provided in this PR, will be much better than nothing for most cases, and can still be overridden in their CR as needed.
The apiserver and etcd requests in this PR are based on current measurements in a dev cluster. The init container resources are a guess because I couldn't figure out how to measure it (its lifetime is too short for kube-state-metrics to catch it).
An entirely alternative approach could be to use defaulting in the CRD to provide these defaults.
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting
> Define default resources for konk

- config/crd/bases/konk.infoblox.com_konkservices.yaml
- examples/konk-service.yaml
This updates the KonkService CRD to require the konk.name and service.name fields.
> Require konk and service name fields in KonkService

- helm-charts/konk-service/templates/configmap.yaml
Fixes this error message:
+ INSTALL=install
+ '[' == install ']'
/mounts/deploy-api-service.sh: line 18: [: ==: unary operator expected
> Avoid bash warning when there are no CRDs to install

- .github/workflows/pr.yaml
- helm-charts/example-apiserver/templates/apiservice-cr.yaml
- helm-charts/example-apiserver/templates/apiservice.yaml
- helm-charts/example-apiserver/templates/deployment.yaml
- helm-charts/example-apiserver/templates/konk-service.yaml
- helm-charts/example-apiserver/values.yaml
- helm-charts/konk-service/templates/deployment.yaml
- test/apiserver/cmd/apiserver/main.go
- test/apiserver/pkg/auth/remoteheader/remoteheader.go
kube-apiserver to example-apiserver tls is now working. delegated auth is still not working and the auth plugin is not being executed
```
k exec -it runner-example-apiserver-diff-konk-service-kubectl-9646678s6snm -- kubectl get apiservice v1alpha1.example.infoblox.com -o yaml | grep caBundle | wc -c
3330
➜  konk git:(dumpRemoteHeaders) k exec -it runner-example-apiserver-diff-konk-service-kubectl-9646678s6snm -- kubectl get contact
No resources found in default namespace.
```
> Dump remote headers

- helm-charts/konk-service/templates/deployment.yaml
Konk's etcd data is not persistent, so after a konk pod restart we lose installed APIServices. This will reinstall them regularly.
> eventually consistent APIService. Fixes ATLAS-8202

- .github/workflows/pr.yaml
- Makefile
- config/crd/bases/konk.infoblox.com_konkservices.yaml
- helm-charts/example-apiserver/templates/konk-service.yaml
- helm-charts/example-apiserver/values.yaml
- helm-charts/konk-operator/templates/deployment.yaml
- helm-charts/konk-service/templates/ingress.yaml
- helm-charts/konk-service/values.yaml
- test/kind.yaml
- watches.yaml
Adds an `ingress` pointing to konk that supports proxied authentication.
Demo:
```
% kubectl -s localhost:80 get contacts
NAME              CREATED AT
contact-example   2020-11-02T21:43:03Z
```
> add ingress

- helm-charts/konk-service/templates/ingress.yaml
I've no idea how the CI passed on #63, but it has been failing since merging #63 due to this path issue. Apparently when only `/api` is defined, `/apis` is not matched by the ingress, resulting in errors like `error: the server doesn't have a resource type "contacts"`:
https://github.com/infobloxopen/konk/pull/88/checks?check_run_id=1354101881#step:11:96
> Fix ingress routes

- helm-charts/konk-service/templates/ingress.yaml
Konk uses TLS between nginx-ingress-controller and its apiserver. The nginx ingress annotation required to configure this TLS server name was not [added until 0.31](https://github.com/kubernetes/ingress-nginx/commit/f9e410458c6cb4c243f301bdb5ffeed31bcc3f96
). Versions earlier than this will report `502 Bad Gateway`.
This PR adds [a workaround](https://github.com/kubernetes/ingress-nginx/issues/4928#issuecomment-574331462
) to effectively make the same change to the nginx.conf.
> Workaround for proxy_ssl_name on ingress-nginx <0.31

- .github/workflows/pr.yaml
Uses a build matrix to test two end-to-end cases: upgrade and fresh install. In the upgrade case, konk-operator is first built and installed from `main`, then again from `HEAD`.
Upgrades have been our most common failure case because we haven't been testing it. The intent of this test is to identify upgrade-related failures before merging.
Docs: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategy
> Test upgrades

- .github/workflows/pr.yaml
- test/apiserver/Dockerfile
- test/apiserver/makefile
This should resolve the error
```
% k -n konk-test logs thayward-apiserver-example-apiserver-7cf57df49-8nkcb -c example-apiserver
Error relocating ./apiserver: __vfprintf_chk: symbol not found
Error relocating ./apiserver: __fprintf_chk: symbol not found
```
> build apiserver in docker

- README.md
- config/crd/bases/konk.infoblox.com_konks.yaml
Added troubleshooting section to readme.
Also added a status field to `kubectl get konks`. Demo:
```
% k get konks -A
NAMESPACE   NAME          STATUS              AGE
default     runner-konk   InstallSuccessful   20h
```
> Add troubleshooting section to readme and status field to kubectl get konks

- .github/workflows/pr.yaml
- test/apiserver/Dockerfile
https://github.com/actions/cache/blob/main/examples.md#go---modules
Also cache the intermediate layers of the docker build for faster builds.
> cache go modules for faster build

- .github/workflows/pr.yaml
Should fix
Unable to reserve cache with key Linux-go-2f61decb61d58b8f42e3320650d30cfd177b83378d5ab2f301b8bbda3ceaab8e, another job may be creating this cache.
> fix cache race

- helm-charts/konk/scripts/provision.sh
- helm-charts/konk/templates/init.yaml
Broken out from #101, this fix loads an existing CA secret before running `kubeadm`, so that certs generated by `kubeadm` are signed by the same original CA and trusted by all the user pods.
> Load existing CA

- config/crd/bases/konk.infoblox.com_konks.yaml
The status column was always showing the second event. This is normally the current status, but in some cases there are three events and the second is not the latest. To show the current status, we should show the final condition, not the second.
```json
% k get konkservice thayward-apiserver-api -o jsonpath='{.status.conditions}' | jq                               kind-konk
[
{
"lastTransitionTime": "2020-11-10T00:57:35Z",
"status": "True",
"type": "Initialized"
},
{
"lastTransitionTime": "2020-11-10T00:57:37Z",
"reason": "InstallSuccessful",
"status": "True",
"type": "Deployed"
},
{
"lastTransitionTime": "2020-11-12T21:35:19Z",
"message": "failed to get candidate release: error validating \"\": error validating data: ValidationError(Deployment.spec.template.spec.initContainers[0].args): …
```
> show latest status in status column

- config/crd/bases/konk.infoblox.com_konkservices.yaml
With helm-operator, the `spec` of the CRD corresponds to values in a helm chart. Over the lifespan of a helm chart, it's typical to add support for new values. If we are to do this with the CRD, and not worry about the CRD upgrade being installed first, we need to allow unknown fields in the CRD spec.
The operator-sdk is aware of this issue and supplies the same option by default: https://github.com/operator-framework/operator-sdk/blob/eb694f23dff2cb9bd3af3df535c35fe5a534c444/internal/plugins/helm/v1/scaffolds/internal/templates/config/crd/crd.go#L108
> Allow unknown fields in CRD for future-proofing

- helm-charts/example-apiserver/templates/space.yaml
- helm-charts/konk-operator/templates/deployment.yaml
- helm-charts/konk-operator/values.yaml
- helm-charts/konk-service/templates/space.yaml
- helm-charts/konk/templates/space.yaml
- watches.yaml
With `space: enabled`, `vaultCommon` must be propagated from the operator
to the konks, konkservices, and example-apiservers. However, `overrideValues`
only supports strings. The important part of `vaultCommon` is the path,
so I've hardcoded the parts other than the path. We're left with a single
string (path) that needs to be propagated.
> propagate vault path

- helm-charts/konk/templates/etcd.yaml
Use carefully, since most fields of the statefulset are immutable:
```
failed upgrade (cannot patch \"runner-konk-etcd\" with kind StatefulSet: StatefulSet.apps \"runner-konk-etcd\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden)
```
> support passing arbitrary values to etcd

- config/crd/bases/konk.infoblox.com_konks.yaml
- config/crd/kustomization.yaml
`helm template --set=crds.create=true` with helm3 doesn't work with CRDs that have these `crd-install` hooks. Since `crd-install` was EOL with helm2, we can remove it.
> drop Tiller support

- .github/workflows/pr.yaml
- Makefile
- helm-charts/konk-service/templates/apiservice-test-deployment.yaml
This new deployment is part of konkservice and periodically attempts to list resource types from the apiserver. If the apiserver doesn't respond properly, the pod indicates unready. This could be used in conjunction with tools like `kubectl wait --for=condition=ready pod -l app.kubernetes.io/component=apiservice-test` for troubleshooting or kube-state-metrics for monitoring and alerting.
> Add a smoke test to konkservice

- helm-charts/konk-service/templates/kubeconfig-certificate.yaml
- helm-charts/konk-service/templates/kubeconfig-deployment.yaml
This change will cause the konk-service-kubeconfig secret to be rebuilt and replaced in the following conditions:
* on konk-service-kubeconfig pod startup (e.g., new konk service created or konk-operator upgraded)
* within 3 minutes of cert-manager renewing the kubeconfig cert
> replace kubeconfig after cert changes. Fixes #192

- .github/workflows/pr.yaml
- helm-charts/konk/scripts/provision.sh
Previously, the default kind version for kind-action v1.1.0 was used. This resolved to [kind v0.9.0](https://github.com/kubernetes-sigs/kind/releases/tag/v0.9.0), which supported Kubernetes v1.13-v1.19. To test against v1.20, I've added an override to use [kind v0.11.1](https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1), which supports Kubernetes v1.14-v1.21. I've also added versions v1.17-v1.21 to the build matrix to cover all the environments we might deploy to.
Relevant error logs:
```
[kube-controller-manager] I0607 17:33:00.445314       1 event.go:291] "Event occurred" object="cert-manager/bulk-konk-ca" kind="Secret" apiVersion="v1" type="Warning" reason="OwnerRefInvalidNamespace" message="ownerRef [apps/v1/Deployment, namespace: cert-manager, name: bulk-konk, uid: …
```
> support Kubernetes v1.20+

- .github/workflows/pr.yaml
- Makefile
- README.md
- helm-charts/README.md.gotmpl
- helm-charts/konk-service/Chart.yaml
- helm-charts/konk-service/README.md
- helm-charts/konk-service/values.yaml
- helm-charts/konk/README.md
- helm-charts/konk/values.yaml
`make chart-readmes` will now use the konk and konk-service values.yaml to generate a readme in markdown format to document the values. Uses https://github.com/norwoodj/helm-docs.
> generate readmes for konk and konk-service charts/CRs

- Makefile
Related ticket: https://github.com/kubernetes-sigs/kind/pull/2347
Note: upgrade test cases fail because they use the ingress-nginx version from `main`, which is unstable.
> fix ci by using stable ingress-nginx

- helm-charts/konk-service/templates/apiservice-configmap.yaml
https://github.com/infobloxopen/konk/commit/d1d5083efe0501aab4193344b6b761587ac215ab#diff-cc3c08c676cade00c3dbb66ef2f36bb4b95288f96bb70f9cfbefddcf4aa08650R82 made the default for `kinds` and `verbs` an `*`. In yaml, this must be quoted or we get errors like this:
```
+ kubectl apply -f /gen/api-service.yaml
namespace/hostapp unchanged
service/hostapp-aggregate-api-apiservice unchanged
apiservice.apiregistration.k8s.io/v1alpha1.onprem.bulk.infoblox.com unchanged
error: error parsing /gen/api-service.yaml: error converting YAML to JSON: yaml: line 12: did not find expected alphabetic or numeric character
```
> quote asterisk in resources and verbs

- .github/workflows/pr.yaml
- Makefile
Konk is [apparently incompatible](https://github.com/infobloxopen/konk/runs/3569079114?check_suite_focus=true) with ingress-nginx v1.0.0 (#233 might fix this). This PR pins the version used in the tests to one prior to the v1.0.0 release until Konk can be updated for v1.0.0 compatibility. It also adds v1.0.0 to the test matrix so we know when we've fixed it.
> add ingress-nginx version to the test matrix

- helm-charts/example-apiserver/templates/konkservice.yaml
- helm-charts/konk-service/templates/apiservice-configmap.yaml
Bugfix:
- apiservice-configmap.yaml was only rendering correctly when 0 or 1 annotation(s) were present on KonkService
> Correct formatting when multiple annotations are present on KonkService.

- Makefile
- helm-charts/konk/scripts/provision.sh
- helm-charts/konk/templates/init.yaml
The etcd and apiserver certs generated by kubeadm are only valid for one year. Every time kubeadm runs, it will renew the certs, but before this change konk would never overwrite the existing certs with the new ones. This PR patches the existing certs with the freshly generated ones when the pod starts and every 90 days.
An alternative approach would be to redesign this process to use cert-manager (#303).
> renew apiserver and etcd certs on konk pod startup

- Makefile
The file we relied on previously to detect the latest ingress-nginx version was removed, so I changed it to use the release tags.
https://github.com/kubernetes/ingress-nginx/pull/8778
> fix CI ingress-nginx installation

- .github/workflows/pr.yaml
- helm-charts/konk/scripts/provision.sh
Info logs from kubectl output like `I0126 00:15:59.895033      10 request.go:645] Throttling request took 1.165292033s` were confusing the `secret_not_found` function. I'm not sure why this function was checking stderr in the first place. All we need is exit code 0 (from `set -e`) and empty stdout.
> fix get secret

- helm-charts/konk/scripts/provision.sh
In cases where the konk has been deleted and reinstalled, but a stale CA still exists in the cert-manager namespace, this will patch it with the latest CA. This allows ClusterIssuers to issue certs for the latest CA.
An alternative approach could be to read the value from the cert-manager namespace and use it to populate the konk namespace instead of replacing it.
> update cluster CA in case it has changed

- helm-charts/konk/scripts/provision.sh
Kubernetes TLS secrets use the paths tls.crt and tls.key. https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets
> fix paths set in #435

- helm-charts/konk-service/templates/kubeconfig-deployment.yaml
`sh` does not support the `$()` syntax, so this probe was always reporting healthy. Fixed by using `bash` instead, which supports the syntax used in the command.
```
% k -n ddi exec -it konk-service-kubeconfig-5dcb64tjzt -- sh -c 'exit $(</tmp/status)'
% echo $?
0
% k -n ddi exec -it konk-service-kubeconfig-5dcb64tjzt -- bash -c 'exit $(</tmp/status)'
error: Internal error occurred: error executing command in container: command terminated with exit code 137
% echo $?
1
```
> fix kubeconfig renewal pod status reporting

- helm-charts/konk-service/README.md
- helm-charts/konk-service/values.yaml
- helm-charts/konk/README.md
- helm-charts/konk/values.yaml
Memory limits should be much higher than anticipated usage. CPU limits are optional, so removed from defaults.
Added defaults to konk-service pods. Closes #240.
> increase default memory limits, remove cpu limits

- .github/workflows/pr.yaml
- Makefile
- helm-charts/example-apiserver/templates/deployment-controller.yaml
- helm-charts/example-apiserver/templates/deployment.yaml
- helm-charts/konk/templates/deployment.yaml
Previously we were only testing the konk apiserver for liveness. This changes it to use the readiness check, which checks a number of things including the etcd connection. See https://kubernetes.io/docs/reference/using-api/health-checks/#api-endpoints-for-health
Also cleaned up a bunch of things in the CI to support testing this.
> check etcd in konk readiness

- helm-charts/konk-service/templates/ingress.yaml
My theory on the broken tests is that the `configuration-snippet` is failing in [ingress-nginx v1.9+](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.9.0).
> drop support for ingress-nginx <0.31

- helm-charts/konk-service/templates/delete-apiservice-deployment.yaml
Observed an error where a long konk-service release name could potentially prevent a delete-apiservice job from triggering as it would surpass the 63 character limit allowed for job names. This PR resolves this by truncating the length of the job name to less than 63 characters.
> Truncate the delete apiservice job name
