charts/konk/templates/deployment.yaml, charts/konk/values.yaml
Accidentally missed these changes in #4
=> fix etcd args

helm-charts/konk-operator/templates/rbac.yaml
Fixes
---apiVersion: rbac.authorization.k8s.io/v1
=> don't eat the newline

.github/workflows/pr.yaml, .gitignore, Makefile, README.md
Add some of the github-actions steps to the makefile.
=> add make rules for standing up kind

Makefile, helm-charts/example-apiserver/templates/apiservice.yaml, helm-charts/example-apiserver/templates/rbac.yaml, helm-charts/example-apiserver/values.yaml, test/apiserver/.gitignore, test/apiserver/makefile
- fix makefile pwd when running from a different directory
- add  test/apiserver push command
=> remove self signed CA from apiservice chart

.github/workflows/pr.yaml, Makefile, helm-charts/example-apiserver/templates/apiservice.yaml, helm-charts/example-apiserver/values.yaml, helm-charts/example-konk-service/templates/konk-service.yaml, helm-charts/konk-service/templates/configmap.yaml, helm-charts/konk-service/templates/deployment.yaml, helm-charts/konk-service/values.yaml
Demo: APIServer is available
```
% k exec -it example-konkservice-konk-service-kubectl-6b7df94766-82px4 -- kubectl get apiservice v1alpha1.example.infoblox.com
NAME                            SERVICE                            AVAILABLE   AGE
v1alpha1.example.infoblox.com   default/runner-example-apiserver   True        32m
```
=> create service in konk

Makefile, config/crd/bases/konk.infoblox.com_konkservices.yaml, examples/konk-service.yaml, helm-charts/example-apiserver/templates/konk-service.yaml, helm-charts/konk-service/templates/configmap.yaml, helm-charts/konk-service/values.yaml
TK-65894 add rbac aggregation to admin and edit roles
should be merged after #55
=> TK-65894 add rbac aggregation to admin and edit roles

helm-charts/konk-service/templates/certificate.yaml, helm-charts/konk/templates/certificate.yaml
setup client SAN to authenticate to konk
fixes #56
=> add service fqdn

.github/workflows/pr.yaml, Makefile, examples/konk.yaml.in, helm-charts/konk/templates/ingress-client-certs.yaml, helm-charts/konk/templates/tests/test-connection.yaml
authN kubectl to the cluster using the certs for nginx
```
+ KUBECONFIG=
+ kubectl api-versions --certificate-authority=/nginx/ca.crt --client-certificate=/nginx/tls.crt --client-key=/nginx/tl
s.key -s https://drew-konk:6443
admissionregistration.k8s.io/v1
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1
...
```
=> test nginx client certificates as part of PR

Makefile
pushing helm chart of example-apiserver to S3 bucket
=> pushing helm chart of example-apiserver

helm-charts/example-apiserver/templates/serviceaccount.yaml
Added the namespace flag to serviceAccount in the example-apiserver chart.
=> Added Namespace field to serviceaccount

README.md
Includes ingress documentation.
=> Add KonkService usage to readme

helm-charts/konk/templates/tests/test-connection.yaml
=> fix flakey test

.github/workflows/pr.yaml, helm-charts/konk/templates/tests/test-connection.yaml
=> remove exit on error

Makefile, helm-charts/example-apiserver/templates/_helpers.tpl, helm-charts/example-apiserver/templates/konk.yaml, helm-charts/example-apiserver/values.yaml
example-apiserver can install its own konk, which makes it easier to deploy.
Sourced from https://github.com/infobloxopen/konk/pull/101#discussion_r520718486
=> BYOK: create konk in example-apiserver

helm-charts/konk/scripts/provision.sh
Fixes #113 
```
NAME                                               TYPE                                  DATA   AGE
runner-konk-etcd-ca                                kubernetes.io/tls                     2      2m29s
```
=> Add etcd ca cert

README.md
The zoom meeting requires people login to zoom and there's a waiting room. That should be sufficient safeguards for unintended guests.
=> note on office hours

.github/workflows/pr.yaml
Adds -x to the defaults documented here:
https://github.com/actions/runner/blob/main/docs/adrs/0277-run-action-shell-options.md#exit-codes--error-action-preference
=> print commands in test workflow

helm-charts/konk-service/templates/kubeconfig-deployment.yaml
Relates to https://infoblox.atlassian.net/browse/ATLAS-9794
=> reference cert files instead of embedding to support dynamic reload

helm-charts/konk-operator/values.yaml
DEMO
The failing pieces are defined in DC or not enforced in our configuration.
=> pass kube-score

helm-charts/konk-service/templates/apiservice-configmap.yaml, helm-charts/konk-service/values.yaml
https://infoblox.atlassian.net/browse/ATLAS-10229 requests a feature to add annotations to the `APIService` created by `KonkService`.
=> support arbitrary annotations on the APIService created by KonkService

.github/workflows/pr.yaml, Makefile, helm-charts/example-apiserver/templates/ingress.yaml, helm-charts/example-apiserver/templates/konkservice.yaml, helm-charts/example-apiserver/values.yaml, helm-charts/konk-service/README.md, helm-charts/konk-service/templates/ingress.yaml, helm-charts/konk-service/values.yaml, helm-charts/konk/README.md, helm-charts/konk/templates/ingress.yaml, helm-charts/konk/values.yaml
Used `helm create` to generate new Ingress templates for apiVersion v1.
=> update ingress for k8s v1.19+

Makefile
cert-manager support matrix: https://cert-manager.io/docs/installation/supported-releases/#supported-releases
=> upgrade cert-manager for k8s v1.22 compatibility

helm-charts/konk-service/templates/ca.yaml, helm-charts/konk-service/templates/certificate.yaml, helm-charts/konk-service/templates/kubeconfig-certificate.yaml, helm-charts/konk/templates/ingress-client-certs.yaml, helm-charts/konk/templates/requestheader.yaml
Background: https://github.com/cert-manager/cert-manager/issues/3458
=> add revisionHistoryLimit for Certificates

.github/workflows/pr.yaml, helm-charts/konk-service/README.md
Based on documentation at https://github.com/EndBug/add-and-commit/issues/389#issuecomment-1116589962
=> fix readme build

.github/workflows/pr.yaml, Jenkinsfile
Supplies the list of charts to the chart signing function.
=> sign charts

.github/workflows/pr.yaml, Dockerfile, Makefile, helm-charts/konk-operator/templates/deployment.yaml
Adds probes to the chart as implemented in https://github.com/operator-framework/operator-sdk/pull/4326/
=> add probes to chart

.github/workflows/pr.yaml, examples/konk-service.yaml, helm-charts/konk-service/templates/apiservice-configmap.yaml, helm-charts/konk-service/templates/delete-apiservice-deployment.yaml
Should resolve https://github.com/infobloxopen/konk/issues/207
=> Added pod def to delete resources in the konk when the corresponding KonkService is deleted

.github/workflows/pr.yaml
Updates the Kubernetes versions used in the PR tests.
=> test against currently supported k8s versions

helm-charts/konk-operator/dashboards/konk-operator.json
Seeing issues with grafana-operator uploading this dashboard to newer versions of Grafana, and I think updating the format (to the export JSON for a dashboard already loaded before Grafana updated) may resolve the issue
=> Update old dashboard format
